"""Locked npm environment assembler — consumer-neutral, host-evidenced
assembly of exact npm dependency closures from reviewed roots and standard
``package-lock.json`` v3 files.

Phase 1 exposes the closed lockfile-v3 model, strict registry-only input
validation, npm range semantics, side-effect-free preflight, and
deterministic assembler/assembler-input identities.  Phase 2 adds the
owner-private assembler cache namespace, opaque npm download cache, safe
staging, canonical hashed tree manifests, and no-follow tree verification.
Phase 3 adds the fixed npm policy, consumer-neutral assembler script,
deterministic Docker run-vector rendering, and structured/cancellable
Docker execution.  Later phases add corporate network projection and
atomic publication.
"""

from __future__ import annotations

from .assembler import (
    ASSEMBLY_TOTAL_TIMEOUT_SECONDS,
    MANIFEST_DEPENDENCY_KEYS,
    NPM_CI_FLAGS,
    NPM_REQUEST_TIMEOUT_MS,
    NPM_RETRY_COUNT,
    NPM_RETRY_MAX_TIMEOUT_MS,
    NPM_RETRY_MIN_TIMEOUT_MS,
    assembler_script_bytes,
    assembler_script_digest,
    npm_policy,
    npm_policy_digest,
    npm_policy_env,
    npm_policy_flags,
)
from .errors import AssemblyTimeoutError, LockedNpmError
from .evidence import (
    AssembledOutputIdentity,
    AssemblerEvidence,
    AssemblerEvidenceBody,
    AssemblyResult,
    canonical_json_bytes,
    compute_assembled_output_identity,
    evidence_body_digest,
    parse_evidence,
    parse_result,
    serialize_evidence,
    serialize_result,
)
from .execution import (
    AssemblyRun,
    CleanupFailure,
    DockerRunExecutor,
    ProcessResult,
    RunExecutor,
    assemble,
    redact,
    redact_docker_argv,
    redact_run_vector,
)
from .identity import (
    AssemblerIdentity,
    AssemblerInputIdentity,
    compute_assembler_identity,
    compute_assembler_input_identity,
    input_identity_digest,
)
from .image_ref import validate_image_reference
from .lockfile import parse_lockfile
from .model import (
    IntegrityLessNode,
    LockfileV3,
    LockPackage,
    OmittedOptional,
    ReviewedRootMetadata,
    RootMetadataKey,
    RootSpec,
    ValidatedAssemblyInput,
)
from .network import (
    CorporateNetworkPolicy,
    validate_credential_free_proxy_url,
)
from .preflight import preflight
from .publication import (
    assemble_environment,
    find_cached_result,
    identity_coordination_lock,
    index_path,
    output_path,
    publish_environment,
    read_index,
    verify_output,
)
from .run_vector import (
    DockerRunVector,
    Mount,
    PROXY_BYPASS_ENV_NAMES,
    NPM_CONFIG_CAFILE,
    PROXY_URL_ENV_NAMES,
    SYSTEM_CA_BUNDLE,
    recheck_assembler_bindings,
    render_docker_argv,
    render_run_vector,
)
from .semver_range import (
    NpmRange,
    NpmRangeError,
    parse_range,
    satisfies,
)
from .smoke import (
    LIFECYCLE_MARKER,
    SMOKE_MARKER_PACKAGE,
    SMOKE_MARKER_VERSION,
    SMOKE_NODE_VERSION,
    SMOKE_NPM_VERSION,
    SMOKE_PLATFORM,
    SMOKE_REPORT_SCHEMA_VERSION,
    extract_image_digest,
    parse_smoke_args,
    render_smoke_report,
    run_smoke,
    serialize_smoke_report,
    smoke_fixture_bytes,
    smoke_fixture_digest,
    smoke_roots,
    verify_installed_closure,
    verify_no_executable_link,
    verify_no_lifecycle_effect,
)
from .storage import (
    AssemblerNamespace,
    assembler_namespace_path,
    prepare_assembler_namespace,
    prepare_identity_lock,
    prepare_staging_workspace,
    remove_staging_workspace,
)
from .streaming import (
    DISPATCHER_DRAIN_BUDGET_SECONDS,
    DiagnosticSink,
    READ_CHUNK_BYTES,
    READER_FAILURE_DETAIL_BYTES,
    REDACTED,
    RedactingStream,
    SINK_CALLBACK_BUDGET_SECONDS,
    SINK_QUEUE_CAPACITY,
    STREAM_STDERR,
    STREAM_STDOUT,
    SinkDispatcher,
    SplitDiagnosticSink,
    StreamChunk,
    StreamReaderFailure,
    StreamingCapture,
    TAIL_BYTES,
    TRUNCATION_NOTICE,
    collect_streams,
    dedupe_secrets,
    longest_secret_length,
    redact_tail,
    redact_text,
)
from .tree import (
    TreeEntry,
    TreeManifest,
    build_tree_manifest,
    canonical_tree_digest,
    parse_manifest,
    serialize_manifest,
    verify_tree,
)
from .validation import make_tree_read_only, validate_assembled_tree

__all__ = [
    "ASSEMBLY_TOTAL_TIMEOUT_SECONDS",
    "AssemblyRun",
    "AssemblyTimeoutError",
    "AssembledOutputIdentity",
    "AssemblerEvidence",
    "AssemblerEvidenceBody",
    "AssemblerIdentity",
    "AssemblerInputIdentity",
    "AssemblerNamespace",
    "AssemblyResult",
    "CleanupFailure",
    "CorporateNetworkPolicy",
    "DISPATCHER_DRAIN_BUDGET_SECONDS",
    "DiagnosticSink",
    "DockerRunExecutor",
    "DockerRunVector",
    "IntegrityLessNode",
    "LIFECYCLE_MARKER",
    "LockedNpmError",
    "LockfileV3",
    "LockPackage",
    "MANIFEST_DEPENDENCY_KEYS",
    "Mount",
    "NPM_CI_FLAGS",
    "NPM_REQUEST_TIMEOUT_MS",
    "NPM_RETRY_COUNT",
    "NPM_RETRY_MAX_TIMEOUT_MS",
    "NPM_RETRY_MIN_TIMEOUT_MS",
    "NpmRange",
    "NpmRangeError",
    "OmittedOptional",
    "ProcessResult",
    "PROXY_BYPASS_ENV_NAMES",
    "NPM_CONFIG_CAFILE",
    "PROXY_URL_ENV_NAMES",
    "READ_CHUNK_BYTES",
    "READER_FAILURE_DETAIL_BYTES",
    "REDACTED",
    "RedactingStream",
    "ReviewedRootMetadata",
    "RootMetadataKey",
    "RootSpec",
    "RunExecutor",
    "SINK_CALLBACK_BUDGET_SECONDS",
    "SINK_QUEUE_CAPACITY",
    "STREAM_STDERR",
    "STREAM_STDOUT",
    "SYSTEM_CA_BUNDLE",
    "SMOKE_MARKER_PACKAGE",
    "SMOKE_MARKER_VERSION",
    "SMOKE_NODE_VERSION",
    "SMOKE_NPM_VERSION",
    "SMOKE_PLATFORM",
    "SMOKE_REPORT_SCHEMA_VERSION",
    "SinkDispatcher",
    "SplitDiagnosticSink",
    "StreamChunk",
    "StreamReaderFailure",
    "StreamingCapture",
    "TAIL_BYTES",
    "TRUNCATION_NOTICE",
    "TreeEntry",
    "TreeManifest",
    "ValidatedAssemblyInput",
    "assemble",
    "assemble_environment",
    "assembler_namespace_path",
    "assembler_script_bytes",
    "assembler_script_digest",
    "build_tree_manifest",
    "canonical_json_bytes",
    "canonical_tree_digest",
    "collect_streams",
    "compute_assembled_output_identity",
    "compute_assembler_identity",
    "compute_assembler_input_identity",
    "evidence_body_digest",
    "dedupe_secrets",
    "extract_image_digest",
    "find_cached_result",
    "identity_coordination_lock",
    "index_path",
    "input_identity_digest",
    "make_tree_read_only",
    "npm_policy",
    "npm_policy_digest",
    "npm_policy_env",
    "npm_policy_flags",
    "longest_secret_length",
    "output_path",
    "parse_evidence",
    "parse_lockfile",
    "parse_manifest",
    "parse_range",
    "parse_result",
    "parse_smoke_args",
    "preflight",
    "prepare_assembler_namespace",
    "prepare_identity_lock",
    "prepare_staging_workspace",
    "publish_environment",
    "read_index",
    "recheck_assembler_bindings",
    "redact",
    "redact_docker_argv",
    "redact_run_vector",
    "redact_tail",
    "redact_text",
    "remove_staging_workspace",
    "render_docker_argv",
    "render_run_vector",
    "render_smoke_report",
    "run_smoke",
    "satisfies",
    "serialize_evidence",
    "serialize_manifest",
    "serialize_result",
    "serialize_smoke_report",
    "smoke_fixture_bytes",
    "smoke_fixture_digest",
    "smoke_roots",
    "validate_assembled_tree",
    "validate_image_reference",
    "validate_credential_free_proxy_url",
    "verify_installed_closure",
    "verify_no_executable_link",
    "verify_no_lifecycle_effect",
    "verify_output",
    "verify_tree",
]
